name: CI/CD to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          npm install
          npm build

      - name: Deploy to S3
        run: |
          # Sync your build artifacts to S3
          aws s3 sync ./path/to/build s3://cloud-training-carolina-linde
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

